import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Gelasio } from 'next/font/google'
import { Bar } from '@/components/Bar'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const gelasio = Gelasio({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-gelasio',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className={`${montserrat.variable} ${gelasio.variable} font-sans`}>
        <Bar.Root />
        {children}
      </body>
    </html>
  )
}
